### ISSUE TITLE
1.0.6-b9 upgrade configuration error - No components loaded

### ISSUE THREAD

**Issue by Kranzy** [StyraHem/ShellyForHASS#171]
When upgrading to 1.0.6-b9 from 1.0.6-b8 I get an error in the log below:

`ERROR (MainThread) [homeassistant.setup] Setup failed for shelly: Unable to import component`

Doing a configuration check gives me the below error:

`Component error: shelly - cannot import name 'ATTR_RESTORED' from 'homeassistant.helpers.entity_registry' (/usr/src/homeassistant/homeassistant/helpers/entity_registry.py)`

Rolling back to beta 8 seems to fix the issue.

Running Home Assistant 103.0 

configuration.yaml is setup only using 
`shelly:`

**Comment by chemelli74** [comment]
Hi @Kranzy, do you mind update at least to 0.140.0 of HA ? They changed quite a lot for device caching and this may affect your setup.

Thank you,

Simone

**Comment by philippsandhaus** [comment]
I just had the same problem and upgrading HA to 0.140.3 solved it for me, thanks.

**Comment by Kranzy** [comment]
Upgraded to 104.3 and beta-9 with no issues. Closing.
