### ISSUE TITLE
Error filling logs after updating to 0.1.1

### ISSUE THREAD

**Issue by Kranzy** [StyraHem/ShellyForHASS#100]
Running Home Assistant 100.2

Updated to the latest version using HACS and log is filling up with the below error.

Was all working fine prior to update.

`Error receiving UDP, 'tuple' object has no attribute 'get', Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 306, in _coap_loop
    ipaddr, code, payload)
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 158, in _update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.7/site-packages/pyShelly/block.py", line 51, in update
    dev.update(data)
  File "/usr/local/lib/python3.7/site-packages/pyShelly/light.py", line 104, in update
    mode = settings.get('mode', 'color')
AttributeError: 'tuple' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 306, in _coap_loop
    ipaddr, code, payload)
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 158, in _update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.7/site-packages/pyShelly/block.py", line 51, in update
    dev.update(data)
  File "/usr/local/lib/python3.7/site-packages/pyShelly/light.py", line 104, in update
    mode = settings.get('mode', 'color')
AttributeError: 'tuple' object has no attribute 'get'`

**Comment by hakana** [comment]
Do you see any deveses and status?

**Comment by Kranzy** [comment]
Yes I still see the devices.

The Shelly 1's which are still showing as switches not lights (im controlling lights) still operate as expected.

The Shelly RGBW2's show status's and do respond, however when turning the light on the switch turned back to off, but then checking again the light did in fact turn on and the switch status updated but it is very slow.

**Comment by genem2** [comment]
Same issue here, if there's anything I can contribute.
Unlike the report above, my HA is not finding the Shelly any longer, so I'm Entity Unavailable.
Reverting to 0.1.0 for now.

```
 2019-11-20 09:22:47 ERROR (CoAP) [pyShelly] Error receiving UDP, 'tuple' object has no attribute 'get', Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 306, in _coap_loop ipaddr, code, payload)
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 158, in _update_bloc block.update(data, ipaddr)
  File "/usr/local/lib/python3.7/site-packages/pyShelly/block.py", line 51, in update dev.update(data)
  File "/usr/local/lib/python3.7/site-packages/pyShelly/light.py", line 104, in update mode = settings.get('mode', 'color')
AttributeError: 'tuple' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 306, in _coap_loop ipaddr, code, payload)
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 158, in _update_block block.update(data, ipaddr)
  File "/usr/local/lib/python3.7/site-packages/pyShelly/block.py", line 51, in update dev.update(data)
  File "/usr/local/lib/python3.7/site-packages/pyShelly/light.py", line 104, in update mode = settings.get('mode', 'color')
AttributeError: 'tuple' object has no attribute 'get' #
```

```
unRAID:
arch | x86_64
dev | false
docker | true
hassio | false
os_name | Linux
python_version | 3.7.4
timezone | America/Los_Angeles
version | 0.101.3
virtualenv | false
```

**Comment by chemelli74** [comment]
@Kranzy, @genem2, can you please retest with 0.1.6b6 ? Please update firmware to latest v1.5.7 as well.

Thank you,

Simone

**Comment by Kranzy** [comment]
Just updated and so far no errors appearing in log. Will let you know if it comes back. Will leave it open for @genem2 to respond.

**Comment by genem2** [comment]
Thanks for the ping on this.  Since the last post I made here, and letting things go, I just realized the errors stopped for me. Not sure I have an explanation.

I checked my RGBW2 and saw the firmware was already at 1.5.7
I updated my shelly folder with your 0.1.6 (Beta 7)
Updated my Docker to 104.3 and restarted everything,

No issues here; all looks good. Thanks.
