### ISSUE TITLE
4 Pro PM not work on 0.3.1.beta2

### ISSUE THREAD

**Issue by danygi79** [StyraHem/ShellyForHASS#611]
Shelly 4Pro PM not recognized on new version

**Comment by hakana** [comment]
I'm running Shelly Pro 4PM and autodiscovery is working fine for me. It uses mDns for autodiscovery so be sure you did not turn it off in the config.

You can also use MQTT or specify the IP address for the devices if it is fixed.

**Comment by danygi79** [comment]
after enable mDns shelly 4pro PM work correctly, but the old shelly 4 pro now no longer respond, or rather, all the sensors can be displayed correctly, but the switches no longer respond, making them unusable, why?

**Comment by danygi79** [comment]
this is log after push a switch on lovelance:

raceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyShelly/block.py", line 279, in _update_status_info
    dev.raise_updated(force_update_devices)
  File "/usr/local/lib/python3.9/site-packages/pyShelly/base.py", line 46, in raise_updated
    callback(self)
  File "/config/custom_components/shelly/device.py", line 58, in _updated
    self._update_ha_state()
  File "/config/custom_components/shelly/device.py", line 51, in _update_ha_state
    self.schedule_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 610, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))  # type: ignore
AttributeError: 'NoneType' object has no attribute 'add_job'
