### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by martin3000** [StyraHem/ShellyForHASS#435]
## Environment

- ShellyForHASS release with the issue: 0.109.6
- Last working ShellyForHASS release (if known): 0.109.6
- Home Assistant Core release with the issue: 0.109.6
- Operating environment (Home Assistant/Supervised/Docker/venv): ubuntu

## Describe the bug
Home Assistant writes out the following error:
Setup failed for shelly: Unable to import component: cannot import name 'async_get_instance' from 'homeassistant.components.zeroconf' (/home/nuc/.local/lib/python3.8/site-packages/homeassistant/components/zeroconf/__init__.py)

## Traceback/Error logs

```txt

```

## Additional context

https://github.com/StyraHem/ShellyForHASS/wiki states:
> This plugin works on HomeAssitant 0.104.0 or newer.
I think Zeroconf-Sharing with the function async_get_instance was introduced later then 0.104.0

See also ä370

**Comment by martin3000** [comment]
This statement in \_\_init__.py should check for the HA version:
> pys.zeroconf = await zeroconf_async_get_instance(self.hass)

**Comment by hakana** [comment]
Will be fixed in next release, 0.2.1b2
